Refactor: Archive Functionality (#13)
* refactor(config-definition): remove upload from archive

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* feat(workspace): define examples of the config archive yaml entries

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* refactor(lifecycle-archive): respect archive methods set as available in workspace

refactor methods into separate posix and s3 modules

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* refactor(lifecycle-archive): add placeholder for http methods

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* feat(results-transfer-daemon): now respects configuration set in workspace

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* feat(lifecycle-archive): s3 move and copy functions

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* test(archive): added

WIP

* build(pre-commit): autoupdate deps

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* style(lifecycle-archive): linting

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* ci(gh-action): trigger ci on pr ready for review

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* test(archive): additional tests

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* ci(gh-action): ci on pr sync

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* feat(utils): new function to add loki handler to logger

linting

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* ci(gh-action): ci python version bumped to 3 10

reason: workflow/definitions/work.py:137: error: X
Y syntax for unions requires Python 3.10

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* build(pyproject): add logging-loki dep

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

* test(pytest): set up requisit initial config

* test(archive): additional tests and code refactor

* feat(archive): read permission command user and group from workspace

* docs(workspaces): added info on archive configuration

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>

---------

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>
Co-authored-by: Shiny [ˈʃaɪni] <charanjotbrar@gmail.com>