ci(gh-action): ci python version bumped to 3 10
reason: workflow/definitions/work.py:137: error: X
Y syntax for unions requires Python 3.10

Signed-off-by: Tarik Zegmott <tzegmott@gmail.com>